image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  CELERY_CONTAINER: "$CI_REGISTRY_IMAGE"_task

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_web:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

build_celery:
  stage: build
  script:
    - docker build -t "$CELERY_CONTAINER" -f Dockerfile-celery .
    - docker push "$CELERY_CONTAINER"
