image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - release
  - deploy

include:
  - template: SAST.gitlab-ci.yml

pylint:
  stage: test
  image: python:latest
  before_script:
    - pip install --no-cache-dir --upgrade --quiet -r requirements.txt
    - pip install pylint --quiet
  script:
    - pylint --extension-pkg-whitelist=pydantic --disable=R0801 app
  allow_failure: true
