image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - release
  - deploy

include:
  - template: SAST.gitlab-ci.yml

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  REF_CONTAINER: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  RELEASE_CONTAINER: ${CI_REGISTRY_IMAGE}:latest

pylint:
  stage: test
  image: python:latest
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install --user pipenv
  script:
    - PIPENV_VENV_IN_PROJECT=1 python -m pipenv install --dev
    - python -m pipenv check
    - python -m pipenv run pylint app
  allow_failure: true

build:
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build --build-arg=BRANCH="${CI_COMMIT_BRANCH}" --build-arg=COMMIT="${CI_COMMIT_SHA}" --build-arg=TAG="${CI_COMMIT_TAG}" --build-arg=USER="${GITLAB_USER_NAME}" -t "${REF_CONTAINER}" .
    - docker push "${REF_CONTAINER}"

release:
  stage: release
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker pull "${REF_CONTAINER}"
    - docker tag "${REF_CONTAINER}" "${RELEASE_CONTAINER}"
    - docker push "${RELEASE_CONTAINER}"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
