FROM python:3.6
COPY requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip; pip install -r /tmp/requirements.txt --upgrade
WORKDIR /app
COPY app /app
ENTRYPOINT celery worker -A tasks.celery
