version: "3"
services:
  dictionary:
    image: registry.gitlab.com/cmu_sidecar/docuscope-dictionary:latest
  couchdb:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=guest
      - COUCHDB_PASSWORD=guest
    ports:
      - "5985:5984"
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  memcached:
    image: memcached:alpine
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COUCHDB_USER=guest
      - COUCHDB_PASSWORD=guest
      - COUCHDB_URL=http://couchdb:5984/
    ports:
      - "4004:80"
    depends_on:
      - celery
      - rabbitmq
      - dictionary