openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mcoking
    url: https://virtserver.swaggerhub.com/CMU_Ringenberg/docuscope-tag/1.0.0
  - description: Docker container
    url: http://{dockerId}:{port}/docuscope-tag/1.0.0
    variables:
      dockerId:
        default: tagger
        description: Id of the docker container for this service.
      port:
        default: '80'
info:
  description: API for accessing the DocuScope tagger.
  version: "1.0.0"
  title: DocuScope Tagger API
  contact:
    email: ringenberg@cmu.edu
  license:
    name: CC BY-NC-SA 4.0
    url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/'
paths:
  /tag_archive:
    post:
      summary: Upload an archive of docx files to be tagged.
      operationId: TagArchive
      description: Starts tagging jobs for each of the docx files in the archive.
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: string
                    format: uuid
                  zipfile:
                    type: string
                    description: Name of the archive file uploaded.
        '400':
          description: 'invalid archive format, invalid file, missing file'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: file
                dictionary:
                  type: string
        description: Archive to process
  /tag_status:
    post:
      summary: Get the status of a tagging job.
      operationId: TagJobStatus
      description: Check on the status of a given job.
      responses:
        '200':
          description: The status of the job.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '404':
          description: Error - Job not found.
#components:
#  schemas:
