env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - { files: ['*.svelte'], processor: 'svelte3/svelte3' }
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions:
    - '.svelte'
  project:
    - './tsconfig.json'
plugins:
  - 'svelte3'
  - '@typescript-eslint'
rules: {}
settings:
  'svelte3/typescript': true

