env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:svelte/recommended
  - plugin:svelte/prettier
  - prettier
overrides:
  - { files: ['*.svelte'], parser: 'svelte-eslint-parser', parserOptions: { parser: "@typescript-eslint/parser" } }
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions:
    - '.svelte'
  project:
    - './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules: {}

